[features]
seeds = false
skip-lint = false
[programs.localnet]
drift_competitions = "9FHbMuNCRRCXsvKEkA3V8xJmysAqkZrGfrppvUhGTq7x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/crisp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
