#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cargo fmt -- --check
cargo clippy -p drift-competitions -- -D warnings -D clippy::unwrap_used -D clippy::expect_used -D clippy::panic
cargo clippy -p drift-competitions --tests -- -D warnings
cargo test --quiet
yarn prettify
yarn lint
cd sdk && yarn run test 
yarn build
